In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
from citipy import citipy
import numpy as np

# Import the API key.
from config import g_key

# Import the requests library.
import requests

from datetime import datetime
import time
from scipy.stats import linregress

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs)
0,0,Olgod,DK,1/4/2020 21:21,55.81,8.63,36.00,80,0,4.70,clear sky,0.0,0
1,1,Vostok,RU,1/4/2020 21:21,46.45,135.83,-7.71,97,100,4.59,light snow,0.0,0
2,2,Faanui,PF,1/4/2020 21:21,-16.48,-151.75,81.45,77,100,12.10,overcast clouds,0.0,0
3,3,Rikitea,PF,1/4/2020 21:21,-23.12,-134.97,77.20,77,67,16.60,broken clouds,0.0,0
4,4,Cape Town,ZA,1/4/2020 21:20,-33.93,18.42,68.00,72,20,4.70,few clouds,0.0,0

In [3]:
# Create a column with Yes or No for rain
city_data_df['rain(y/n)'] = np.where(city_data_df['Rain inches(last 3hrs)']>0, 'yes', 'no')
city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs),rain(y/n)
0,0,Olgod,DK,1/4/2020 21:21,55.81,8.63,36.00,80,0,4.70,clear sky,0.00,0,no
1,1,Vostok,RU,1/4/2020 21:21,46.45,135.83,-7.71,97,100,4.59,light snow,0.00,0,no
2,2,Faanui,PF,1/4/2020 21:21,-16.48,-151.75,81.45,77,100,12.10,overcast clouds,0.00,0,no
3,3,Rikitea,PF,1/4/2020 21:21,-23.12,-134.97,77.20,77,67,16.60,broken clouds,0.00,0,no
4,4,Cape Town,ZA,1/4/2020 21:20,-33.93,18.42,68.00,72,20,4.70,few clouds,0.00,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556,556,San Jorge,PH,1/4/2020 21:23,11.98,124.82,70.93,95,35,4.05,light rain,0.56,0,yes
557,557,Vasyshcheve,UA,1/4/2020 21:23,49.83,36.33,32.00,93,75,6.71,light shower snow,0.00,0,no
558,558,Nome,US,1/4/2020 21:23,30.04,-94.42,68.00,34,1,10.29,clear sky,0.00,0,no
559,559,Ilhabela,BR,1/4/2020 21:23,-23.78,-45.36,76.84,85,100,5.14,light rain,2.13,0,yes
560,560,Bodden Town,KY,1/4/2020 21:23,19.28,-81.25,86.00,79,75,3.36,shower rain,0.00,0,no

In [4]:
# Create a column with Yes or No for snow
city_data_df['snow(y/n)'] = np.where(city_data_df['Snow inches(last 3hrs)']>0, 'yes', 'no')
city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs),rain(y/n),snow(y/n)
0,0,Olgod,DK,1/4/2020 21:21,55.81,8.63,36.00,80,0,4.70,clear sky,0.00,0,no,no
1,1,Vostok,RU,1/4/2020 21:21,46.45,135.83,-7.71,97,100,4.59,light snow,0.00,0,no,no
2,2,Faanui,PF,1/4/2020 21:21,-16.48,-151.75,81.45,77,100,12.10,overcast clouds,0.00,0,no,no
3,3,Rikitea,PF,1/4/2020 21:21,-23.12,-134.97,77.20,77,67,16.60,broken clouds,0.00,0,no,no
4,4,Cape Town,ZA,1/4/2020 21:20,-33.93,18.42,68.00,72,20,4.70,few clouds,0.00,0,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556,556,San Jorge,PH,1/4/2020 21:23,11.98,124.82,70.93,95,35,4.05,light rain,0.56,0,yes,no
557,557,Vasyshcheve,UA,1/4/2020 21:23,49.83,36.33,32.00,93,75,6.71,light shower snow,0.00,0,no,no
558,558,Nome,US,1/4/2020 21:23,30.04,-94.42,68.00,34,1,10.29,clear sky,0.00,0,no,no
559,559,Ilhabela,BR,1/4/2020 21:23,-23.78,-45.36,76.84,85,100,5.14,light rain,2.13,0,yes,no
560,560,Bodden Town,KY,1/4/2020 21:23,19.28,-81.25,86.00,79,75,3.36,shower rain,0.00,0,no,no

In [5]:
#Get the data types
city_data_df.dtypes

City_ID                     int64
City                       object
Country                    object
Date                       object
Lat                       float64
Lng                       float64
Max Temp                  float64
Humidity                    int64
Cloudiness                  int64
Wind Speed                float64
Current Description        object
Rain inches(last 3hrs)    float64
Snow inches(last 3hrs)      int64
rain(y/n)                  object
snow(y/n)                  object
dtype: object

In [6]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [7]:
# Ask the customer to add a minimum and maximum temperature value.Filter the DataFrame for minimum and maximum temperature preferences, and if the rain or snow accumulation is 0 inches or not using conditional statements.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_q = str(input("Do you want it to be raining? (yes/no)"))
snow_q = str(input("Do you want it to be snowing? (yes/no)"))

What is the minimum temperature you would like for your trip? 40
What is the maximum temperature you would like for your trip? 85
Do you want it to be raining? (yes/no)no
Do you want it to be snowing? (yes/no)no

In [8]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & \
                                       (city_data_df["rain(y/n)"] == rain_q) & \
                                       (city_data_df["snow(y/n)"] == snow_q)]
preferred_cities_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs),rain(y/n),snow(y/n)
2,2,Faanui,PF,1/4/2020 21:21,-16.48,-151.75,81.45,77,100,12.10,overcast clouds,0.0,0,no,no
3,3,Rikitea,PF,1/4/2020 21:21,-23.12,-134.97,77.20,77,67,16.60,broken clouds,0.0,0,no,no
4,4,Cape Town,ZA,1/4/2020 21:20,-33.93,18.42,68.00,72,20,4.70,few clouds,0.0,0,no,no
5,5,Sampit,ID,1/4/2020 21:21,-2.54,112.95,75.43,97,100,1.16,overcast clouds,0.0,0,no,no
6,6,Biltine,TD,1/4/2020 21:21,14.53,20.93,62.91,20,0,17.56,clear sky,0.0,0,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,547,Kasempa,ZM,1/4/2020 21:23,-13.46,25.83,62.69,98,100,4.79,overcast clouds,0.0,0,no,no
548,548,Nuevo Progreso,US,1/4/2020 21:23,26.05,-97.95,75.00,21,40,3.36,scattered clouds,0.0,0,no,no
552,552,Sun Valley,US,1/4/2020 21:22,39.60,-119.78,57.20,42,1,11.41,clear sky,0.0,0,no,no
554,554,Touros,BR,1/4/2020 21:23,-5.20,-35.46,82.40,69,20,13.87,few clouds,0.0,0,no,no
558,558,Nome,US,1/4/2020 21:23,30.04,-94.42,68.00,34,1,10.29,clear sky,0.0,0,no,no

In [9]:
preferred_cities_df.count()

City_ID                   311
City                      311
Country                   309
Date                      311
Lat                       311
Lng                       311
Max Temp                  311
Humidity                  311
Cloudiness                311
Wind Speed                311
Current Description       311
Rain inches(last 3hrs)    311
Snow inches(last 3hrs)    311
rain(y/n)                 311
snow(y/n)                 311
dtype: int64

In [10]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
Hotelvacation_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
Hotelvacation_df["Hotel Name"] = ""
Hotelvacation_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Faanui,PF,81.45,overcast clouds,-16.48,-151.75,
3,Rikitea,PF,77.20,broken clouds,-23.12,-134.97,
4,Cape Town,ZA,68.00,few clouds,-33.93,18.42,
5,Sampit,ID,75.43,overcast clouds,-2.54,112.95,
6,Biltine,TD,62.91,clear sky,14.53,20.93,
...,...,...,...,...,...,...,...
547,Kasempa,ZM,62.69,overcast clouds,-13.46,25.83,
548,Nuevo Progreso,US,75.00,scattered clouds,26.05,-97.95,
552,Sun Valley,US,57.20,clear sky,39.60,-119.78,
554,Touros,BR,82.40,few clouds,-5.20,-35.46,
558,Nome,US,68.00,clear sky,30.04,-94.42,

In [11]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

In [12]:
 # Iterate through the DataFrame.
for index, row in Hotelvacation_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        Hotelvacation_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [13]:
Hotelvacation_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Faanui,PF,81.45,overcast clouds,-16.48,-151.75,Bora-Bora Pearl Beach Resort & Spa
3,Rikitea,PF,77.20,broken clouds,-23.12,-134.97,Pension Maro'i
4,Cape Town,ZA,68.00,few clouds,-33.93,18.42,Southern Sun Waterfront Cape Town
5,Sampit,ID,75.43,overcast clouds,-2.54,112.95,Aquarius Boutique Hotel Sampit
6,Biltine,TD,62.91,clear sky,14.53,20.93,Hôtel Trois Étoiles de Biltine
...,...,...,...,...,...,...,...
547,Kasempa,ZM,62.69,overcast clouds,-13.46,25.83,Miracle Guest House
548,Nuevo Progreso,US,75.00,scattered clouds,26.05,-97.95,Hotel Las Flores
552,Sun Valley,US,57.20,clear sky,39.60,-119.78,Panther Valley RV Park
554,Touros,BR,82.40,few clouds,-5.20,-35.46,INN NEW HORIZON
558,Nome,US,68.00,clear sky,30.04,-94.42,Silver Spur Mobile Home & RV Park

In [14]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
Hotelvacation_df.to_csv(output_data_file, index_label="City_ID")

In [15]:
# Add a marklayer for the vacation spots.
locations = Hotelvacation_df[["Lat", "Lng"]]
max_temp = Hotelvacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Set the info box categories
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
</dl>
"""

In [17]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in Hotelvacation_df.iterrows()]

In [18]:
# Add a pop-up marker for each city.
locations = Hotelvacation_df[["Lat", "Lng"]]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))